Rewrite workflow recipes

diff --git a/.github/workflows/cmake-linux.yml b/.github/workflows/cmake-linux.yml
--- a/.github/workflows/cmake-linux.yml
+++ b/.github/workflows/cmake-linux.yml
@@ -9,6 +9,7 @@ on:
 env:
   # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
   BUILD_TYPE: Release
+  TIME: 00000000-000000
 
 jobs:
   build-linux:
@@ -19,46 +20,57 @@ jobs:
 
     steps:
     - uses: actions/checkout@v3
+    - name: Configure environment
+      run: |
+           echo "HOME=$HOME" >> $GITHUB_ENV
     - name: Install dependencies
       run: |
            sudo apt-get update
-           sudo apt-get install cmake-extras qt6-base-dev qt6-connectivity-dev qt6-tools-dev qt6-tools-dev-tools zip
+           sudo apt-get install -y cmake-extras zip libegl1-mesa-dev libfuse2
+           sudo apt-get install -y qt6*
           
     - name: Configure CMake
       # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
       # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
       run: cmake -B ${{github.workspace}}/build \
                   -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
-                  -DCMAKE_INSTALL_PREFIX=/usr/
+                  -DCMAKE_INSTALL_PREFIX=${HOME}/qbrainwave-app/
                   
     - name: Build
       # Build your program with the given configuration
       run: |
           echo ${{github.workspace}}
-          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
+          echo ":: BUILD ::"
+          cmake --build ${{github.workspace}}/build
+          echo ":: Install ::"
+          cmake --install ${{github.workspace}}/build --prefix ~/qbrainwave-app/usr
 
     - name: Build Package
       run: |
            cd ${{github.workspace}}/build
-           mkdir -p artifacts/qbrainwave
-           mkdir appdir/
-           wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
-           wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
+           mkdir -p ${HOME}/artifacts/qbrainwave
+           wget -q https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
            chmod +x linuxdeploy*.AppImage
            ./linuxdeploy-x86_64.AppImage \
-                -e ./bin/qbrainwave \
+                -e ${HOME}/qbrainwave-app/usr/bin/qbrainwave \
                 -i ${{github.workspace}}/desktop/qbrainwave-icon.svg \
                 -d ${{github.workspace}}/desktop/qbrainwave.desktop \
                 --output appimage \
-                --appdir appdir/ \
-                --plugin qt
-            cp qbrainwave*.AppImage artifacts/tuningTrainer || echo "FAILED"
-            cp ${{github.workspace}}/src/harpsichord.wav artifacts/tuningTrainer || echo "FAILED"
+                --appdir ${HOME}/qbrainwave-app/ 
+            echo ":: Copy :rocket: ::"    
+            cp -v qbrainwave*.AppImage ${HOME}/artifacts/ || echo "FAILED"
+
+#    - name: Add timestamp
+#      run: |
+#           cd ~/artifacts
+#           TIME=$(date +%Y%m%d-%H%M%S)
+#           echo "TIME=$TIME" >> $GITHUB_ENV
+#           mv qbrainwave*.AppImage qbrainwave-${TIME}.AppImage
     
     - name: Upload qbrainwave-linux
       uses: actions/upload-artifact@v3.0.0
       with:
-        name: qbrainwave-linux
-        path: ${{github.workspace}}/build/artifacts
+        name: qbrainwave-linux-${{ env.TIME }}
+        path: ${{ env.HOME }}/artifacts
         
 
diff --git a/.github/workflows/cmake-macos.yml b/.github/workflows/cmake-macos.yml
--- a/.github/workflows/cmake-macos.yml
+++ b/.github/workflows/cmake-macos.yml
@@ -1,4 +1,4 @@
-name: Build MacOS Monterey
+name: Build MacOS
 
 on:
   push:
@@ -10,76 +10,68 @@ on:
 env:
   # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
   BUILD_TYPE: Release
-
+  TIME: 00000000-000000
 
 jobs:
   build-macos:
     # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
     # You can convert this to a matrix build if you need cross-platform coverage.
     # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
-    runs-on: macos-latest
+    runs-on: macos-12
 
     steps:
     - uses: actions/checkout@v3
-    - name: Print system info
-      run: |
-           uname -m
-           ls /usr/local
 
-    - name: Install dependencies
+      
+    - name: Prepare environment
       run: |
-           brew update
-           rm /usr/local/bin/2to3
-           rm /usr/local/bin/idle3
-           rm /usr/local/bin/pydoc3
-           rm /usr/local/bin/python3
-           rm /usr/local/bin/python3-config
-           brew upgrade
-           brew install qt@6 tree cmake extra-cmake-modules
-           tree --charset ascii /usr/local/Cellar/qt/ > ~/qt-tree.txt
-           ls /opt >> ~/dirs.txt
-           ls /usr/local >> ~/dirs.txt
+           if [[ -x ~/artifacts ]]; then 
+           rmdir -Rf ~/artifacts
+           fi
+           mkdir ~/artifacts
+    
+    - name: Install QT
+      run: |
+           pip3 install aqtinstall
+           aqt install-qt -O ~/Qt mac desktop 6.4.0
+           aqt install-qt -O ~/Qt mac desktop 6.4.0 -m qtconnectivity
            
     - name: Configure CMake
       # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
       # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
       run: |
-           cmake -B ${{github.workspace}}/build \
-                 -DQt6_DIR=$(brew --prefix qt6)/lib/cmake/Qt6 \
+           ~/Qt/6.4.0/macos/bin/qt-cmake -B ${{github.workspace}}/build \
                  -DCMAKE_INSTALL_PREFIX=qbrainwave.app \
-                 -DCMAKE_OSX_ARCHITECTURES="x86_64" \
+                 -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" \
                  -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} 
-
+          
     - name: Build
       # Build your program with the given configuration
       run: |
-           echo "Github workspace=${{github.workspace}}"
-           echo "PWD=${PWD}"
            cd ${{github.workspace}}/build
            make
-    
+
     - name: Build Package
       run: |
            cd ${{github.workspace}}/build
-           $(brew --prefix qt6)/bin/macdeployqt qbrainwave.app || echo "Macdeploy FAILED"
+           ~/Qt/6.4.0/macos/bin/macdeployqt qbrainwave.app || echo "Macdeploy FAILED"
+           file qbrainwave/Contents/MacOS/qbrainwave || echo "No such file"
            codesign -dv --verbose=4 qbrainwave.app || echo "Codesign FAILED"
-           tree --charset ascii .
            
     - name: Prepare Artifact
       run: |
            cd ${{github.workspace}}/build
-           if [[ -x artifacts ]]; then 
-           rmdir -Rf artifacts
-           fi
-           mkdir artifacts
-           cp -Rv qbrainwave.app artifacts/qbrainwave.app
-           cp ~/qt-tree.txt artifacts
-           cp ~/dirs.txt artifacts
+           cp -Rv qbrainwave.app ~/artifacts/qbrainwave.app
 
+    - name: Add timestamp
+      run: |
+           cd ~/artifacts
+           TIME=$(date +%Y%m%d-%H%M%S)
+           echo "TIME=$TIME" >> $GITHUB_ENV
+           mv qbrainwave.app qbrainwave-${TIME}.app
 
     - name: Upload tuningTrainer-mac
       uses: actions/upload-artifact@v3.0.0
       with:
-        name: qbrainwave-macos
-        path: ${{github.workspace}}/build/artifacts
-        
+        name: qbrainwave-macos-universal-${{ env.TIME }}
+        path: ~/artifacts
