Create universal package

diff --git a/.github/workflows/cmake-macos.yml b/.github/workflows/cmake-macos.yml
--- a/.github/workflows/cmake-macos.yml
+++ b/.github/workflows/cmake-macos.yml
@@ -18,61 +18,43 @@ jobs:
     # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
     # You can convert this to a matrix build if you need cross-platform coverage.
     # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
-    runs-on: macos-11
+    runs-on: macos-12
 
     steps:
     - uses: actions/checkout@v3
-    - name: Install dependencies
+    - name: Fetch dependencies
       run: |
-           brew install tree cmake extra-cmake-modules
-           brew install pcre2 harfbuzz freetype
-           brew install cmake ninja python
-
-    - name: Prepare QT
+           mkdir -p ~/brew-mod/{x86_64,arm64}
+           brew fetch --force --bottle-tag=monterey --deps qt@6
+           for i in $(brew --cache)/downloads/*x86_64*
+           do 
+           tar -vxzf $i -C ~/brew-mod/x86_64
+           rm $i
+           done
+           brew fetch --force --bottle-tag=arm64_monterey --deps qt@6
+           for i in $(brew --cache)/downloads/*arm64*
+           do 
+           tar -vxzf $i -C ~/brew-mod/arm64
+           rm $i
+           done
+    
+    - name: Create universal
       run: |
-           cd ~
-           git clone git://code.qt.io/qt/qt5.git qt6
-           cd qt6
-           git checkout 6.2.4
-           ./init-repository
-           cd ..
-           mkdir qt6-release
-           cd qt6-release
-           ../qt6/configure \
-               -release \
-               -prefix ./qtbase \
-               -nomake examples \
-               -nomake tests \
-               QMAKE_APPLE_DEVICE_ARCHS=arm64;x86_64 \
-               -opensource \
-               -confirm-license \
-               -skip qt3d \
-               -skip qtwebengine
-
-
+           cd ~/brew-mod
+           ${{github.workspace}}/scripts/ci/macos/convert_to_universal.sh
+           
     - name: Configure CMake x86_64
       # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
       # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
       run: |
+           QT6_CMAKE=$(find ~/brew-mod/universal -iname Qt6Config.cmake)
+           QT6_PATH_LOCAL=${QT6_CMAKE%Qt6Config.cmake}
            cmake -B ${{github.workspace}}/build \
-                 -DCMAKE_PREFIX_PATH=~/qt6-release \
+                 -DQt6_PATH=${QT6_PATH_LOCAL} \
                  -DCMAKE_INSTALL_PREFIX=qbrainwave.app \
-                 -DCMAKE_OSX_ARCHITECTURES="x86_64" \
+                 -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" \
                  -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} 
-      
-#    - name: Configure CMake ARM
-#      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
-#      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
-#      run: |
-#           cmake -B ${{github.workspace}}/build-arm64 \
-#                 -DQt6_DIR=~/brew-arm64/Qt/6*/lib/cmake/Qt6 \
-#                 -DAUTOMOC_EXECUTABLE=$(brew --prefix qt6)/share/qt/libexec/moc \
-#                 -DAUTOUIC_EXECUTABLE=$(brew --prefix qt6)/share/qt/libexec/uic \
-#                 -DAUTORCC_EXECUTABLE=$(brew --prefix qt6)/share/qt/libexec/rcc \
-#                 -DCMAKE_INSTALL_PREFIX=tuningTrainer.app \
-#                 -DCMAKE_OSX_ARCHITECTURES="arm64" \
-#                 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} || echo "CMake ARM64 failed"
-    
+          
     - name: Build x86_64
       # Build your program with the given configuration
       run: |
@@ -81,19 +63,11 @@ jobs:
            cd ${{github.workspace}}/build
            make
 
-#    - name: Build ARM
-#      # Build your program with the given configuration
-#      run: |
-#           echo "Github workspace=${{github.workspace}}"
-#           echo "PWD=${PWD}"
-#           cd ${{github.workspace}}/build-arm64
-#           make
-    
     - name: Build Package
       run: |
            cd ${{github.workspace}}/build
-           ~/qt6-release/bin/macdeployqt qbrainwave.app || echo "Macdeploy FAILED"
-           tree --charset ascii .
+           $(find ~/brew-mod/universal -iname macdeployqt) qbrainwave.app || echo "Macdeploy FAILED"
+           file qbrainwave/Contents/MacOS/qbrainwave || echo "No such file"
            
     - name: Prepare Artifact
       run: |
@@ -108,6 +82,6 @@ jobs:
     - name: Upload tuningTrainer-mac
       uses: actions/upload-artifact@v3.0.0
       with:
-        name: qbrainwave-macos
+        name: qbrainwave-macos-universal
         path: ${{github.workspace}}/build/artifacts
         
