Fix #0001

diff --git a/.github/workflows/cmake-msvc.yml b/.github/workflows/cmake-msvc.yml
--- a/.github/workflows/cmake-msvc.yml
+++ b/.github/workflows/cmake-msvc.yml
@@ -23,8 +23,17 @@ jobs:
     steps:
     - name: Setup Base MINGW env
       run: |
+           echo on
            mkdir D:\artifacts
            echo %%PATH%% > D:\artifacts\path.txt
+           7zip -v || echo "7zip not found"
+           curl -v || echo "7zip not found"
+           wget -v || echo "wget not found"
+           unzip -v || echo "unzip not found"
+           tar -v || echo "tar not found"
+           pip -V || echo "pip not found"
+           python -V || echo "python not found"
+           cmake --version || echo "Cmake not found"
 
     - name: Upload qbrainwave-win-${{ env.TIME }}.zip
       uses: actions/upload-artifact@v3.0.0
